### ISSUE TITLE
Forecast cost GB: InvalidTypeError if global investors bonus is empty

### ISSUE THREAD

**Issue by kTitan** [FOE-Tools/FOE-Tools.github.io#120]
Goto the Forecast cost GB Site and delete the default value of „0“, because you want to enter something useful ;)

Immediately after deleting the value, this error is shown:
```
InvalidTypeError

Invalid type for parameter "investorPercentage[0]" of SubmitRange(from, to, investorPercentage, gb), expected "number" but was "string"
```

**Comment by Heziode** [comment]
This issue are fixed with #121.
