### ISSUE TITLE
Where's the mention of test3r?

### ISSUE THREAD

**Issue by artfiedler** [FOE-Tools/FOE-Tools.github.io#128]
Seems this site started as a copy of test3r's foe-tools... why did you take and use the same name as they did? http://foe-tools.000webhostapp.com kinda weird there is no mention of this on the site. I remember test3r had released that site in October about 3 months before this site, I got it bookmarked. I heard test3r's new site is going to be released around the end of January

**Comment by Heziode** [comment]
Hi Arthur,

It is not mentionned because this FOE-Tools are not based on the work of test3r. The website is developped from scratch.

Sincerly,

Heziode

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by artfiedler** [comment]
Why the same name?

**Comment by Heziode** [comment]
The name is only for optimise the [SEO](https://en.wikipedia.org/wiki/Search_engine_optimization).

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
