### ISSUE TITLE
[GB-Investment] Table cut off / use fullscreen

### ISSUE THREAD

**Issue by kTitan** [FOE-Tools/FOE-Tools.github.io#162]
Would it be possible to change the display of the table in GB invest screen to use fullscreen?
Currently the whole screen has big borders, and the table is not completely displayed (at least on iPad screens)

![IMG_0110](https://user-images.githubusercontent.com/516661/54091109-573afc80-437c-11e9-9679-91b148dff229.jpeg)

**Comment by Heziode** [comment]
:rofl: It'is between widescreen (desktop, etc.) and smal screen (smartphone) so… I will change to display the table like on small screen.

**Comment by Heziode** [comment]
I will release this next week. I have some other fix to to before ;)
