### ISSUE TITLE
New design is awful

### ISSUE THREAD

**Issue by vvval** [FOE-Tools/FOE-Tools.github.io#169]
New design is super ugly for mobiles. Now each row in the owners tab contains column labels, and the numbers in each cell now are not aligned vertically due to different label length. So instead of seing all 5 rows with pretty-formatted data at one screen I see 2 rows with a huge mess of numbers and text

**Comment by Heziode** [comment]
Yop, can you send a screenshot please ?

**Comment by vvval** [comment]
![62A17703-015C-486A-A822-279338FCC09E](https://user-images.githubusercontent.com/11367763/54193036-50ba9b00-44ca-11e9-9680-7aa527195166.png)
![3FE55E58-35BF-4204-93A6-2FF22FA061B3](https://user-images.githubusercontent.com/11367763/54193037-50ba9b00-44ca-11e9-90fb-ea7116eedf04.png)

**Comment by Heziode** [comment]
Indeed, this is not the expected display. I will fix that in the week…

**Comment by Heziode** [comment]
Normally, you should get that:

![Screenshot_20190311_185209_com android chrome](https://user-images.githubusercontent.com/16735076/54240018-2f36cf00-451d-11e9-8166-1a42551dcba1.jpg)

**Comment by Heziode** [comment]
I suppose that you are on an apple device, with safari ?

**Comment by jimmcclintock** [comment]
The multi-box format without the summary table (that was previously there) is a major step backwards in UX. Don't fix what wasn't broken!

**Comment by soodvarun** [comment]
On mobile, can we get option to see the table like before? The new “card” display seems to be simply repeating the information and it’s turned into lot of scrolling and mind bending. I am using iPad with chrome and display looks like what was reported at the beginning.

**Comment by jimmcclintock** [comment]
Agree with previous commenters. Prior version with table was MUCH better. This "new" design is a major step backwards. Don't fix what isn't broken!

**Comment by Heziode** [comment]
Ok,

I will add a switch to let the choice.

**Comment by soodvarun** [comment]
> Ok,
> 
> I will add a switch to let the choice.

Kindly make the table as default and the new cards as an option via switch. Although I am not sure if cards display is needed at all. Your call.

**Comment by Heziode** [comment]
I have do that because scrollwide on smartphone (for website) is not a normal behavior / UX (my point of vue)

**Comment by jimmcclintock** [comment]
Not sure what you mean by last comment, but prior design did not require any scroll. The default view was the desired view - the summary table showing place, default reward, required owner FP to lock, total rewards to donor, and donation bonus thread rate. That's the mimimum must-have info - the rest is nice to have, but not at the expense of screwing up that summary table.

**Comment by jimmcclintock** [comment]
Thanks for listening and being willing to make changes!

**Comment by Heziode** [comment]
It is released

**Comment by soodvarun** [comment]
Thank you for taking feedback!
