### ISSUE TITLE
BoundExceededError

### ISSUE THREAD

**Issue by DaEgo** [FOE-Tools/FOE-Tools.github.io#179]
hi,
i type something wrong and this happens : 

BoundExceededError
"participationSum + ownerPreparation" should not be > than 330 for parameters "participationSum" and "ownerPreparation" of ComputeLevelInvestment(levelCost, currentDeposits, yourParticipation, otherParticipation, yourArcBonus, fpTargetReward)

i can go back to basic side (babel) but this error still stand there when i open the page again,
reload this page does not fix it

mfg

**Comment by Heziode** [comment]
Ok... Try to clearing your cookie cache of foe tools.
I Will check that asap

**Comment by Heziode** [comment]
And which value have you entered and on which field ?

**Comment by DaEgo** [comment]
i really dont remember, but i can repat this error

it happens when self invested FPs and investors added and THEN i add more self invested than the build limit

 

i test it with Himeji Castle and it happens again

 

1. Number of FPs currently put by the owner (max 1210) - i put 500 in

2. i add investor 10

3. i add investor 100

4. i add investor 500

5. i set the number of FPs set by self owner to 1000

and the error is :

"participationSum + ownerPreparation" should not be > than 1210 for parameters "participationSum" and "ownerPreparation"

of ComputeLevelInvestment(levelCost, currentDeposits, yourParticipation, otherParticipation, yourArcBonus, fpTargetReward)

 


so when i add investors and THAN i set higher self invested than me+investors = error

 

sry for my spelling, i am german :-)

 


Gesendet: Donnerstag, 14. März 2019 um 09:45 Uhr
Von: "Quentin Dauprat" <notifications@github.com>
An: "FOE-Tools/FOE-Tools.github.io" <FOE-Tools.github.io@noreply.github.com>
Cc: Chris <daego@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [FOE-Tools/FOE-Tools.github.io] BoundExceededError (#179)


And which value have you entered and on which field ?

**Comment by Heziode** [comment]
Okay, I see, so you did it expressly too :P
I will fix that that tonight.

**Comment by DaEgo** [comment]
thx!
But I wonder that nobody found this bug before!?
OK, that's me, i was my whole life time a bug hunter  😂
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.

**Comment by Heziode** [comment]
Your are the first to report this issue
