### ISSUE TITLE
Forecast profit for GB from investor view

### ISSUE THREAD

**Issue by Cycloth** [FOE-Tools/FOE-Tools.github.io#183]
Currently, the forecast page provides helpful information for the owner.

I suggest to add a functionality, which displays the best case profit from an investors view.
For example, the expected profit for taking the first place (1.85 with 80 lvl arc) in every level from level 10 to 60 for an arc should be a four-digit figure, if I remember correctly.

In other words: When I (arc 80) help a specific player level up his arc, how much can I expect?

**Comment by Heziode** [comment]
Something like [that](https://foe-tools.github.io/fr/gb-investment/The_Arc/) ?

**Comment by Cycloth** [comment]
Almost. Yes, I forgot about this page, sorry.
But it does not answer my question, because I can not specify the investor bonus.
For me, the normal investment would be a placement of 1.85 with an arc bonus of 1.9 so I make a small profit.
E.g. For level 10 the investor would made a profit of 5 FP = 5%
Currently it only shows how much profit the investor makes when placing safe (only makes sense between ~ 30 and 60), or when arc bonus = placement factor.

**Comment by Heziode** [comment]
I can add a field to specify the investor percentage.That should answer your question, shouldn't it?

**Comment by Cycloth** [comment]
Yes, that would be nice

**Comment by Heziode** [comment]
Oki, I will probably add that this week-end.

**Comment by Heziode** [comment]
@Cycloth,

Do you mean something like that ?:

![gb-investment-investors](https://user-images.githubusercontent.com/16735076/54872101-557f2900-4dbf-11e9-80ab-939d0b4f4243.png)

**Comment by Cycloth** [comment]
Yes, exactly.
