### ISSUE TITLE
Conduct QA on "Show Snipe" feature to verify its accuracy

### ISSUE THREAD

**Issue by roberttrone** [FOE-Tools/FOE-Tools.github.io#197]
#Inaccurate numbers have been provided, recently, suggesting users invest too few forge points to "lock," despite locking being the entire point.  Specifically engage QA on accuracy when there are >2 investors.

**Comment by Heziode** [comment]
Can you provide an example ?

**Comment by Heziode** [comment]
@roberttrone, can you provide an example (or permalink) and tejj me what did you expect about the values please ?

**Comment by roberttrone** [comment]
I think it’s a UI feature that just requires some critical thinking, but it doesn’t say if donators have “locked” places.



On Apr 3, 2019, at 2:20 AM, Quentin Dauprat <notifications@github.com<mailto:notifications@github.com>> wrote:


@roberttrone<https://github.com/roberttrone>, can you provide an example (or permalink) and tejj me what did you expect about the values please ?

**Comment by Heziode** [comment]
@roberttrone the 2.32.1 is out, it contains a fix in GB Investment. Can you tell me if your bug is always present ?

**Comment by Heziode** [comment]
Assume fixed.
