### ISSUE TITLE
GB statistics of other players

### ISSUE THREAD

**Issue by soalless** [FOE-Tools/FOE-Tools.github.io#212]
Hi, is it possible with this tool to get statistics of other players GB, sort by how many FP's are left to completion of level, etc? If not, is there a tool out there that can? Thanks

**Comment by Heziode** [comment]
Hi,

Nop this tool cannot do that.The closest tool to it is [Forge DB](https://www.forge-db.com/).

**Comment by soalless** [comment]
can this do it? https://github.com/m3talstorm/foe-decryption

it talks about making requests about information, but not sure

**Comment by Heziode** [comment]
A part of this repo is outdated due to FOE do no longer use Flash. Secret key can be found on the scipts send to client. But this in not really legal according to the [11.1 and 11.3 of InnoGames GTC](https://legal.innogames.com/portal/en/agb).

**Comment by soalless** [comment]
If its against the rules, then Forge DB tool is also done against the rules? as i understand it also scrapes the game for great buildings

**Comment by Heziode** [comment]
Yep, that's where I don't understand why it's allowed.

**Comment by soalless** [comment]
I see. So its not a flash based game anymore? What does it use now? Javascript?

**Comment by Heziode** [comment]
Yep, it is a "HTML5" game now.
Adobe will drop Flash support in 2020 so InnoGames have switch to a "HTML5". Which lib it uses, framework, etc. I don t know.

**Comment by Cycloth** [comment]
They use [Haxe](https://haxe.org/) and [OpenFL](https://www.openfl.org/)

> Yep, that's where I don't understand why it's allowed.

It's not allowed, but they can't do much against the (private) data scraping. 

> So its not a flash based game anymore?

There is an option in game to enable flash mode.

**Comment by soalless** [comment]
I see. Is it hard to scrape a GB list off of their game? What do you need for it? Also i guess it takes a lot of time no? Since forge db tool only reports gbs of high ranking players

**Comment by Heziode** [comment]
I can't tell you, I don't know…

**Comment by soalless** [comment]
I wonder why foe db doesnt charge anything for their data though, would they get sued by the creator of the game if they did?

**Comment by Heziode** [comment]
> I wonder why foe db doesnt charge anything for their data though, would they get sued by the creator of the game if they did?

Yep because they would violate the 11.4 of InnoGames GTC.

**Comment by soalless** [comment]
So, if its free they cant be touched? what about donations? they cant touch donations too?

**Comment by Heziode** [comment]
> So, if its free they cant be touched?

If they really wanted to close it, they would have already done it, I think.

> They cant touch donations too?

Nope, they can't touch donations because it is not necessary to donate to access to the whole service provided by the platform. But, this can work **only** if the user can access to the whole service provided by the platform, isn't it violate the 11.4.

> And what about bots then, theyre not allowed, but I saw some being sold. Also, I have used one myself for another game, Grepolis.

This is completly illegal. The seller can be prosecuted, and the user banned.
