### ISSUE TITLE
Can't submit survey

### ISSUE THREAD

**Issue by edu2004eu** [FOE-Tools/FOE-Tools.github.io#220]
I've filled out all the checkbox / radio type fields, and some textareas where applicable. The submit button is disabled.

I've also tried filling out every single input / textarea to see if the button can be clicked, but it's still disabled.

Using latest Chrome on Ubuntu.

**Comment by Heziode** [comment]
Only field with a star '__*__' are required.

It's works for me on Chromium and Firefox on Archlinux. Have you a addblock or something like that that block completly Google ? Because I use Google Recaptcha (hidden version) for form validation.

**Comment by Heziode** [comment]
@edu2004eu, any change ?

**Comment by edu2004eu** [comment]
Yup, the submit button is now enabled.

**Comment by Heziode** [comment]
Ok.
It is very weird because I do not have change anything in the survey.
