### ISSUE TITLE
Top menu is badly broken on iPads 

### ISSUE THREAD

**Issue by soodvarun** [FOE-Tools/FOE-Tools.github.io#237]
Hi, I am using site on iPad and after recent changes the menu bar on the top is broken.

When I expand the menu for “Tool” or “Statistics” it hides behind the main panel in the center. It’s virtually impossible to reach certain items and you have to very carefully scroll in that tiny space to reach to an item.

![IMG_0085](https://user-images.githubusercontent.com/1323253/58750814-9a70ad00-844b-11e9-9fed-f75952558723.jpeg)

Can we fix this please?

Thanks!

**Comment by Heziode** [comment]
Hum,

Have you the same behavior when the menu is not fixed ? You can modify it in global settings (cog icon in the main menu).

**Comment by Heziode** [comment]
I have tested that in device (iPad) vue in chromium on laptop, and indeed, there is an issue.

A work around for now is to switch to `no` the value of "Main menu always visible" in "Global settings" accessible from the cog icon on the top menu.

**Comment by soodvarun** [comment]
Thanks for providing the workaround. It seems to have fixed the issue. 

Btw, this issue is also there on iPhones.

Another problem on iPhones is that you can’t “collapse” tools and statistics sections. They are always expanded to full which can lead to problem reaching out lower menu items. In other words, clicking on “down arrow” does not collapse the menu.

**Comment by Heziode** [comment]
Can you send a screenshot ?

**Comment by Heziode** [comment]
> On iPhones you can’t “collapse” tools and statistics sections. They are always expanded to full which can lead to problem reaching out lower menu items. In other words, clicking on “down arrow” does not collapse the menu.

@soodvarun this behavior is due to the current behavior in the CSS framework that I use ([Bulma](https://bulma.io/documentation/components/navbar/))
