### ISSUE TITLE
Promotion messages not showing correct numbers!!!

### ISSUE THREAD

**Issue by Ferlinaj** [FOE-Tools/FOE-Tools.github.io#241]
New promotion messages showing up with default reward #'s instead of Rewards with rate #'s
![Screenshot_20190610-185258](https://user-images.githubusercontent.com/51683790/59234189-39667900-8bb1-11e9-91f6-f50f75951255.png)

**Comment by Heziode** [comment]
Hi,

It is a bug, I am on it.
