### ISSUE TITLE
Kostenrechner (enhancement)

### ISSUE THREAD

**Issue by SkateScout** [FOE-Tools/FOE-Tools.github.io#269]
Eine sehr gute Verbesserung wäre wenn der Kostenrechner die Werte der Eigenen Arche als Default übernimmt und beim Leveln anpasst. Bzw wenn sie Manual geändert werden auch zwischen zwei Browser Sitzungen abspeichert. Das Abspeichern wäre auch für den Eigenanteilsrechner Klasse.

**Comment by Heziode** [comment]
Hi, can you reword the issue in english please ?

**Comment by SkateScout** [comment]
It would be an great improvement if the cost calculator and own investment calculator can take the values from the arche for as default and change it if the arche is leveling. Only if changed manual to other values keep the manual value. And store these values like the selected data transmission over the sessions. Maybe also an idea would to mark the places where the fp's of the player are to low.

**Comment by Heziode** [comment]
Currently, I do no have values of GB bonus. I only have level cost and FP reward.

You can use "Your Arc bonus" to have information about what you can gain/loss by investing on places, by setting to "Yes" the field "Show Spot/Snipe".

**Comment by SkateScout** [comment]
I mean ton store the arc bonus (in this example 22%) permanent and if it matche the owner arc, change it when the arc levels. This avoid to place fp because after browser restart the percent value was reseted.
![image](https://user-images.githubusercontent.com/919349/65724184-24eeb380-e0b0-11e9-81af-078cece693bf.png)

**Comment by Heziode** [comment]
This is the goal of "% of global investors bonus (arc bonus)" and "% of investors bonus (arc bonus)".

[See example from your screenshot](https://foe-tools.github.io/gb-investment/Oracle_of_Delphi/?gbi_tab=0&gbi_l=7&gbi_oi=0&gbi_ipg=22&gbi_ip=%5B%5D&gbi_p1=22&gbi_p2=22&gbi_p3=22&gbi_p4=22&gbi_p5=22&gbi_pFree1=1&gbi_pFree2=1&gbi_pFree3=1&gbi_pFree4=1&gbi_pFree5=1&gbi_px=Yoratheon&gbi_sx=farie%20up&gbi_sn=1&gbi_dgbn=1&gbi_sl=1&gbi_spx=true&gbi_ssx=false&gbi_ss=1&gbi_yab=90&gbi_sosp=true&sp_lc=370&sp_cd=0&sp_yp=0&sp_op=0&sp_yab=90&sp_ftr=0).

**Comment by Heziode** [comment]
@SkateScout, 

So, saving data to retrieve them after browse restart is already implemented, and now using the browser local storage instead of cookies.

For the part about ‘’When I level up the Arc GB, it changes the value of the field…’’. Here, you mean the field is ‘’your arc bonus’’, isn’t ?

**Comment by SkateScout** [comment]
Yes and it is already implemented. So this topic can be closed. I lost it from my screen.
