### ISSUE TITLE
Fullscreen (bug)

### ISSUE THREAD

**Issue by SkateScout** [FOE-Tools/FOE-Tools.github.io#271]
If you select full-screen in the bottom left area the FOE-Tools menu got lost.
When you use F11 for full screen the menu does not get lost.
I think this is only an small glitch.

**Comment by Heziode** [comment]
On which browser ?

**Comment by SkateScout** [comment]
Google Chrome ist auf dem neuesten Stand.
Version 77.0.3865.90 (Offizieller Build) (64-Bit)

**Comment by Heziode** [comment]
> If you select full-screen in the bottom left area

Where do you set the full-screen. There is no button to toggle full-screen at the bottom left on chrome.

**Comment by SkateScout** [comment]
The second button from the right where the mouse points to it is part of the game that force the chrome to full screen mode.
![image](https://user-images.githubusercontent.com/919349/65724416-a0e8fb80-e0b0-11e9-9ac2-83709bcbc990.png)

**Comment by Heziode** [comment]
Hum… I cannot reproduce.

This is not a major bug, it's not very inconvenient.

**Comment by SkateScout** [comment]
Not important.
