### ISSUE TITLE
New line for promotion message

### ISSUE THREAD

**Issue by thewaiters** [FOE-Tools/FOE-Tools.github.io#28]
Hello,
it would be great when the tool provides a new promotion line like this

"Castel del Monte P4(10) P3(19) P2(67) P1(133)"

The direction of the places are changed, because so its easier for an foe app user to delete a place.

**Comment by Heziode** [comment]
Good idea, I will plan that for v2

**Comment by Heziode** [comment]
What do you think of adding a checkbox button in table for each position to add or remove each place to the promotion message ?

**Comment by thewaiters** [comment]
Hey, i think the calculator should be fast. It takes to long to click for each place. Normally you need all places or the first + the second. All places when you want that other shall go on p1-p5. The first and the Second often between lv30-60 that neighbors don‘t catch the places.

So you need only this two options. It can be simply separate lines.

I would add a button after each line to copy the promotion massage. That would be fast and you need no manuell selection anymore. So it would be great when you add the line from my initial post and place a button behind. :-) THX

**Comment by Heziode** [comment]
@thewaiters,

I have do that:

![6845e216-3593-4ee6-bc36-e7301682c07d](https://user-images.githubusercontent.com/16735076/39405786-3e6f2ae6-4bac-11e8-948c-dff23839cf32.png)


You can click for each place for quick add this place in promotion message (last column of the table) and you have also a button at the right of each promotion message to automatically copy this promotional message (for browsers that support this feature. So, normally, all recent browsers)
