### ISSUE TITLE
Forecast cost start level is wrong.

### ISSUE THREAD

**Issue by Philio** [FOE-Tools/FOE-Tools.github.io#281]
On the forecast cost page, the starting level in the text is always 1 more than the selected level. The calculation seems to be correct though.

![image](https://user-images.githubusercontent.com/237850/68026115-8b19b800-fca6-11e9-8fa7-854fb249ce94.png)

**Comment by Heziode** [comment]
I Philio,

I fix that today and the fix will be released tomorrow.
