### ISSUE TITLE
promotion message builder places broken

### ISSUE THREAD

**Issue by vqt123** [FOE-Tools/FOE-Tools.github.io#289]
promotion message builder no longer showing numbers as of today

**Comment by vqt123** [comment]
clearing my browser cache fixed the problem. Seems to be no other way .

**Comment by Heziode** [comment]
Hi vqt,

I have updated the promotion message builder and the behavior of "Include in copy box" into the last update (released yesterday).

If the place are not shown anymore it is because it is set to "no" in "Include in copy box".
