### ISSUE TITLE
Suffix not adding up, must have it hard-coded in message builder

### ISSUE THREAD

**Issue by burianvlastimil** [FOE-Tools/FOE-Tools.github.io#298]
This custom config I used:
```
{"customFields":{},"prefix":"Wise","suffix":"Thanks","displayGbName":true,"showLevel":true,"useShortGbName":true,"reversePlacesOrder":true,"placeSeparator":", ","place":"Pos#${PI}=${PV}","message":"${GBN}: ${P}"}
```

It, however, refuses to show the "Thanks" part (suffix), I gave up trying now, implemented this workaround:

```
{"customFields":{},"prefix":"Wise","suffix":"","displayGbName":true,"showLevel":true,"useShortGbName":true,"reversePlacesOrder":true,"placeSeparator":", ","place":"Pos#${PI}=${PV}","message":"${GBN}: ${P}. Thanks"}
```

It works as expected, just pointing out some error in your message builder possibly if not my human error ;)

**Comment by Heziode** [comment]
Hi @burianvlastimil,

The control of Suffix and Prefix are in "Promotion Message" tab.

![image](https://user-images.githubusercontent.com/16735076/73721693-1cc11780-4725-11ea-91c6-3a926ba3686e.png)

The crossed-out eye means that it is not displayed. You can click on the icon to show it.

**Comment by burianvlastimil** [comment]
Let me check in 5 minutes.

**Comment by burianvlastimil** [comment]
No, you misunderstand maybe. I have created a template above, and even with NOT-crossed that icon, it has no effect on the template, how to add an image here in comment?

**Comment by Heziode** [comment]
To import an image, just drag and drop it in the reply.

**Comment by burianvlastimil** [comment]
![msg_builder](https://user-images.githubusercontent.com/14146682/73722464-dcfb2f80-4726-11ea-92d0-a575f410b202.png)

**Comment by Heziode** [comment]
Ok, I understand your missunderstanding.

You need to feel the Suffix field here in "Promotion message" tab.
The prefix and suffix field in Promotion message builder is only to give a sort of "placeholder" for user. I maybe need to remove it from the builder or add a note about that.

**Comment by burianvlastimil** [comment]
I see, ok very well.
