### ISSUE TITLE
Forecast Tool with Cape as example issue

### ISSUE THREAD

**Issue by burianvlastimil** [FOE-Tools/FOE-Tools.github.io#300]
I very well might - again - misunderstand your tool(s), this time the Forecast Tool with [Cape as example](https://foe-tools.github.io/gb-forecast-cost/?gbfc_gb=Cape_Canaveral&gbfc_f=11&gbfc_t=60&gbfc_ipg=90&gbfc_cp=0&gbfc_fp=150&gbfc_ai=&gbfc_p1=90&gbfc_p2=90&gbfc_p3=90&gbfc_p4=90&gbfc_p5=90)

Here's your tool's claim:
To go from level 10 to 60 of "Cape Canaveral", the owner has to invest 13,111 FPs. Total cost of levels: 87,955 FPs. With bonus investments, you'll save 35,489 FPs.

What I do not understand is: 87955-13111 should equal to 74844 saved, or what did I miss again?
Thank you.

**Comment by Heziode** [comment]
Hi,

It is because you have forgot to take in account the default investment:
87955-13111 = 74844, the total number of FPs that investors shall put. It is a combination of default investment, without arc Bonus (39355) and the number of FPs that you should put with arc bonus (35489). So 39355+35489 = 74844.

**Comment by burianvlastimil** [comment]
I'm still confused, sorry... so in a 1.9 thread where everyone is giving full boost, I will have to invest more than those 13111? suffice yes or no and you can close this issue, thank you very much!

**Comment by Heziode** [comment]
13111 is the expected preparation of the owner when investors invest at 1.9. So yes, you will have to "only" invest 13111 FPs on your Cap to prepare those level.

**Comment by burianvlastimil** [comment]
thank you a bunch!
