### ISSUE TITLE
GB Investment - Show only secured places switch

### ISSUE THREAD

**Issue by akotulu** [FOE-Tools/FOE-Tools.github.io#301]
Toggeling switch will leave all the promotion message fields without investments. Setting switch back to YES will not toggle the `Include in copy boxes` to enabled.

Safari Version 13.0.5 (13608.5.12)

Also tested on Opera, same case.

**Comment by Heziode** [comment]
If set to **Yes**, this field shall be used with "Number of FPs currently put by the owner" and "Add investor" fields. It automatically switch places when it secured by the owner and not already taken.

If it set to **No**, you need to toggle each place manually.

Anyway, when set the field to **No**, it seems more intuitive to re-enable all places. I change this behavior to set to **Yes** all places when switching this field to **No**.

**Comment by akotulu** [comment]
It seems more logical yes. Thank you. Really awesome project and cleanly done.
