### ISSUE TITLE
Brazilian Portuguese Translation

### ISSUE THREAD

**Issue by JhonnyBn** [FOE-Tools/FOE-Tools.github.io#327]
How to create a second translation for Portuguese? Because Brazilian Portuguese is very different from Portuguese in Portugal
I tried FOE-Tools Translation (Weblate) "Start new translation" button but got an error "The given language is filtered by the language filter."
Then I reviewed [CONTRIBUTING.md](https://github.com/FOE-Tools/FOE-Tools.github.io/blob/develop/CONTRIBUTING.md) and it says that I need an ISO 639-1 standard code, but brazilian portuguese doesn't have one. Most sites use the [language tag](https://en.wikipedia.org/wiki/Language_localisation) pt-BR as the language code, could I use that?

**Comment by JhonnyBn** [comment]
FOE-Tools Translation (Weblate) error: 

![image](https://user-images.githubusercontent.com/29382833/84583085-e24e4200-adca-11ea-8e16-36e478f4e783.png)

The language selection menu could look like this with PT-BR translation

![image](https://user-images.githubusercontent.com/29382833/84583080-d1053580-adca-11ea-8205-2bc6267f47ff.png)

**Comment by Heziode** [comment]
Hi @JhonnyBn, 

I need to do a refactor of many "small" things of the website. The translation is part of it (this will be the next big update).

> Then I reviewed CONTRIBUTING.md and it says that I need an ISO 639-1 standard code, but brazilian portuguese doesn't have one. Most sites use the language tag pt-BR as the language code, could I use that?

This page will be updated to follow the [BCP47](https://en.wikipedia.org/wiki/IETF_language_tag) instead.

---

I will create a copy of Portuguese translation for Brazilian Portuguese, so that you can translate part the differ from Portuguese using Weblate.

**Comment by Heziode** [comment]
Brazilian Portuguese added to Weblate. You can start translation \o/.

Tell me when you are complete the translation to add it to the website.

**Comment by JhonnyBn** [comment]
> Hi @JhonnyBn,
> 
> I need to do a refactor of many "small" things of the website. The translation is part of it (this will be the next big update).
> 
> > Then I reviewed CONTRIBUTING.md and it says that I need an ISO 639-1 standard code, but brazilian portuguese doesn't have one. Most sites use the language tag pt-BR as the language code, could I use that?
> 
> This page will be updated to follow the [BCP47](https://en.wikipedia.org/wiki/IETF_language_tag) instead.
> 
> I will create a copy of Portuguese translation for Brazilian Portuguese, so that you can translate part the differ from Portuguese using Weblate.

Thank you for the quick response and please keep up the good work!
I've started translating but it's more time-consuming than I expected, I hope to finish it this week.

**Comment by Heziode** [comment]
Hi @JhonnyBn, 

Any progress on the translation ?

**Comment by JhonnyBn** [comment]
I completely forgot about it, sorry!
Will continue now

**Comment by Heziode** [comment]
Ok :)

I will release an update this sunday. If you haven't finished by then it doesn't matter, it will be in the next update.

**Comment by JhonnyBn** [comment]
Done!
Please add it to the next update, i would love to see the translation in the site :D

**Comment by Heziode** [comment]
Ok,

I will add this language into the release of today.

**Comment by JhonnyBn** [comment]
Updated in weblate

**Comment by Heziode** [comment]
Yep, this will be into the next release.

Updates come out maximum every sunday.
An important fix (like website not accessible :joy:) can be released before sunday.
