### ISSUE TITLE
Rename dynamic tower to truce tower

### ISSUE THREAD

**Issue by Styxxy** [FOE-Tools/FOE-Tools.github.io#329]
The "Dynamic Tower" got renamed a while back to "Truce Tower".
Would be good to rename it here as well.

**Comment by Heziode** [comment]
There is some translation in pending for weeks.

I will try to find a moment this week to release it.

**Comment by Heziode** [comment]
The new name is in [2.67.0](https://github.com/FOE-Tools/FOE-Tools.github.io/releases/tag/v2.67.0)
