### ISSUE TITLE
Option to include places with 0 FP reward (GB Investment)

### ISSUE THREAD

**Issue by yohancourbe** [FOE-Tools/FOE-Tools.github.io#332]
At the moment, when reward of GB is 0 FP, it's excluded from GB Investment calculation. It would be nice to have an option to add them in the calculation for 1 FP (parameterized ?)

**Comment by Heziode** [comment]
You can do that by adding an investor with the amount you want (here 1FP).

<img width="471" alt="Capture d’écran 2020-07-11 à 12 55 08" src="https://user-images.githubusercontent.com/16735076/87222652-cad88980-c375-11ea-925d-ff5d643a3d7a.png">
