### ISSUE TITLE
Multi-tab sync issue

### ISSUE THREAD

**Issue by Bertrand67** [FOE-Tools/FOE-Tools.github.io#339]
I'm using multiple tabs in Chrome browser for GB Investment. After closing browser the last state is not showing. It's obvious that cookie saving is not working.

**Comment by Heziode** [comment]
Hi,

The state are not store in cookies, but in local storage.

Which is the version of Chrome ?
On which operating system ?

**Comment by Bertrand67** [comment]
Hi,

Thank you for your reply.
I have Chrome version 85.0.4183.83 (official build) (64 bits) on Windows 10 version 2004 (os version 19041.450).

**Comment by Heziode** [comment]
Ok, I can reproduce it.

This bug is on all browsers. The code is not designed to be used with multiple tabs.
I will take a look to find a way to solve this issue, but it can take a while.

The fix will not be into the release of today.

**Comment by Heziode** [comment]
However, I think this issue can be avoided with a feature I will add in the coming months. But I can try to find a fix before the making this feature.
