### ISSUE TITLE
Forecast cost GB inaccurate

### ISSUE THREAD

**Issue by TheNightsFall** [FOE-Tools/FOE-Tools.github.io#350]
In the "Estimated time to reach level using swap threads" section of the Forecast cost GB, it's often very buggy. Whenever I input how many FPs I have on my current level, the number is off the rails inaccurate, and when I delete that input and reset to zero it goes to infinity. Thank you, this has been a helpful resource in the past for me.

![before](https://user-images.githubusercontent.com/63215794/93033822-854a6e00-f5fd-11ea-8621-5733f59c74a8.png)
![during](https://user-images.githubusercontent.com/63215794/93033831-8aa7b880-f5fd-11ea-884c-0728a1e8fef1.png)
![final](https://user-images.githubusercontent.com/63215794/93033834-8d0a1280-f5fd-11ea-8e62-10b92f7aa2e1.png)

**Comment by Heziode** [comment]
Hi @TheNightsFall, 

Thank you to point this out.

Attention, you shall use the line "Estimated time to reach the level:" to find out how long it will take to mount a GM using a 1.9, 1.85, etc. group.

The second line, "Estimated time to reach the level using a swap threads (5/10/20/50/100 FPs, etc.):" is only indicative to see how much time is wasted to use this kind of threads.

**Comment by Heziode** [comment]
The fix will be in the next release that will be published this Sunday.
