### ISSUE TITLE
Graph resources

### ISSUE THREAD

**Issue by FJduFou** [FOE-Tools/FOE-Tools.github.io#368]
Hello,
I would like to make some modification to the graph in order to adapt it to the dark theme, for that I need to know a few things:
Where is the style information for the graph text?
Where is the style information for the graph tooltip?
Thank you in advance

**Comment by Heziode** [comment]
I'm on it.
It's pretty boring, since it's require to set the configuration in JS, because I use [Chart.js](https://www.chartjs.org)

**Comment by FJduFou** [comment]
ok :)

**Comment by FJduFou** [comment]
Okay, so I take this opportunity to suggest you add blur in the tooltip to make the background cleaner and readable

**Comment by Heziode** [comment]
Not sure I can do it, the theme modifications seems quite limited with this framework.
