### ISSUE TITLE
Persistent drop-down menu after selection

### ISSUE THREAD

**Issue by FJduFou** [FOE-Tools/FOE-Tools.github.io#376]
Where: In the menu
What: After selecting an item from the drop-down menu, it does not close when the page change has been made, it does not close when the other menu is opened.
Idea: Add an event that kills the menu after selection
Screenshot:
[https://i.imgur.com/1jxgWV3.gif](https://i.imgur.com/1jxgWV3.gif)

**Comment by Heziode** [comment]
I don't understand the problem.

Your image (gif) is supposed to be animated?

**Comment by FJduFou** [comment]
Yes, the gif is animated, click on the link and wait a bit, it's easier to understand with the gif ...
In this situation I am not clicking outside the drop down menu, it is important

**Comment by Heziode** [comment]
The gif is not animated on my side.

**Comment by FJduFou** [comment]
I have no problem at home, strange ...
How can I show it to you otherwise?

**Comment by FJduFou** [comment]
I'm trying this
![Cyoo5rrIyH](https://user-images.githubusercontent.com/46401854/99911135-9ba63180-2cf2-11eb-8d22-6fc25036a832.gif)

**Comment by Heziode** [comment]
Ok, I see, I will investigate that ASAP.
