### ISSUE TITLE
Vertical non-alignment in language selection

### ISSUE THREAD

**Issue by FJduFou** [FOE-Tools/FOE-Tools.github.io#379]
_**Where:**_ In the language selection drop-down menu
**_What:_** Parameter: "**.media-content {{lang.displayName}}**" is not vertically aligned to previous / following
**_Idea:_** Using an array to manage vertical alignment or using an image to replace the symbol with a country flag
**_Screenshot:_**
![image](https://user-images.githubusercontent.com/46401854/99957005-49632000-2d87-11eb-8aba-faf3c3592178.png)

**Comment by FJduFou** [comment]
If you need flags:[https://commons.wikimedia.org/wiki/Category:National_flags_by_country]( https://commons.wikimedia.org/wiki/Category:National_flags_by_country)

**Comment by Heziode** [comment]
> If you need flags: https://commons.wikimedia.org/wiki/Category:National_flags_by_country

I deliberately did not put an image to optimize the size of the pages.
I use the flag icon provided by the system font. So, on windows or depending on your conf on linux, this display letter, otherwise it display the icon of the flag, [that can be something like this](https://emojipedia.org/flags/).

**Comment by FJduFou** [comment]
This is what I imagine::
![image](https://user-images.githubusercontent.com/46401854/99970312-ec259980-2d9b-11eb-8293-272241326bc3.png)
If not, why not use my idea for an alignment table?

**Comment by FJduFou** [comment]
> I deliberately did not put images to optimize the size of the pages.
Px size or storage size?

**Comment by Heziode** [comment]
Storage size, bandwidth optimization (for smartphone users).

**Comment by FJduFou** [comment]
> If not, why not use my idea for an alignment table?

This is possible?

**Comment by Heziode** [comment]
These are two different problems, or I didn't understand :joy:

Alignment is to vertically align text and flags to prevent the issue shown in the screenshot, isn't ?
If this is the case, so, yes using alignment table, or something provided by the CSS framework used ([Bulma](bulma.io/)), and modify the [language-selector component](https://github.com/FOE-Tools/FOE-Tools.github.io/blob/develop/components/language-selector/template.pug).

**Comment by FJduFou** [comment]
The initial idea was to use flags to solve the problem simply, you have to raise 2 problems (size and the other) ...
So in this case, it is therefore better to use an alignment table so that the "**.media-content {{lang.displayName}}**" starts in the same place as the others ... I would gladly do that but I don't know that well
