### ISSUE TITLE
Add notification to encourage people to participate to the translation

### ISSUE THREAD

**Issue by Heziode** [FOE-Tools/FOE-Tools.github.io#381]
Add a notification (like survey) to encourage the community to participate to the translation.

This notification should be displayed according to constraints like:

- The status of the translation of this language is less than 80%.

**Comment by FJduFou** [comment]
#380

**Comment by FJduFou** [comment]
My apologies, but it's **half a reinvention of the wheel**: the ... (_drum roll_) "**JavaScript Popup Boxes**" (_symbale!_)
It comes straight from the good old school **w3schools** that you can find [here](https://www.w3schools.com/js/js_popup.asp) ...
**Simple, efficient, fast, light** and as you said: "_keeping the OS / Browser default style_", and like me I said: "_it's not customizable and it annoys me_" ...
