### ISSUE TITLE
Visual problem in the NavBar

### ISSUE THREAD

**Issue by FJduFou** [FOE-Tools/FOE-Tools.github.io#382]
**Where:** In the NavBar
**What:** The style effect applied in the PR #371 does not apply when mouse hovers over a drop-down item (and sorry, i don't see where it comes from, i can't find where the style of this element is)
**Idea:** No
**Screenshot:**
![G3SzJIQycT](https://user-images.githubusercontent.com/46401854/100148638-4b1f0780-2e9d-11eb-8b74-ca8e92bb61db.gif)

**Comment by Heziode** [comment]
This is the default style that comes from Bulma.

**Comment by FJduFou** [comment]
Why use Bulma and not just do it in classic HTML / CSS or classic Pug / SCSS?

**Comment by Heziode** [comment]
> Why use Bulma and not just do it in classic HTML / CSS or classic Pug / SCSS?

Have you ever developed websites (professionally speaking)?
Don't reinvent the wheel. That's why the framework exists, because doing the whole style by hand is tedious.

**Comment by Heziode** [comment]
And that's also why I'm going to migrate to Tailwind, to avoid edge effects by using a utility CSS framework.

**Comment by FJduFou** [comment]
> Have you ever developed websites (professionally speaking)?
> Don't reinvent the wheel. That's why the framework exists, because doing the whole style by hand is tedious.

Never
Ok...

**Comment by FJduFou** [comment]
I don't found how to repair this, sorry 😶

**Comment by Heziode** [comment]
It's not too annoying to the eye.
I think we can leave the state like this.
In any case, this will disappear when I would have moved on to Tailwind.

**Comment by FJduFou** [comment]
Like you want
