### ISSUE TITLE
Tutorial is broken

### ISSUE THREAD

**Issue by FJduFou** [FOE-Tools/FOE-Tools.github.io#386]
**Where:** In the tutorial
**What:** Dark mode borders are white
The size of the upper part is too large
The square used to make the arrow is badly positioned
Not enough space to view the video
Reading area too small
Idea: Repair all this point by point 😜
**Screenshot:**
![image](https://user-images.githubusercontent.com/46401854/100235805-24a8ad00-2f2d-11eb-9912-c686acbe8acb.png)
![image](https://user-images.githubusercontent.com/46401854/100235839-2d997e80-2f2d-11eb-8261-ef99bdf81457.png)

**Comment by Heziode** [comment]
This is related to [Shepherd.js](shepherdjs.dev/), the framework that I use to create the interactive tutorial.
The bug should be in this framework… honestly, I don't have the courage to fight with this framework :joy:

Maybe trying the new major release of Shepherd, but, who says majour release says breaking change.

**Comment by FJduFou** [comment]
_That's why I prefer to reinvent the wheel but it's not optimal ..._ 😂
Else, why not **cut off access to the tutorial** while waiting for a potential migration (so as not to delete the code)? 
Because I think that, in my opinion, this one is not very useful ... (I personally discovered this tutorial button by looking in the code for what the 2 **.mp4** files were used for ...)

**Comment by Heziode** [comment]
> _That's why I prefer to reinvent the wheel but it's not optimal ..._ 😂

C'est pas faux…

> Else, why not **cut off access to the tutorial** while waiting for a potential migration (so as not to delete the code)?
> I personally discovered this tutorial button by looking in the code for what the 2 **.mp4** files were used for ...

Damn it ! I added a big blue button.

I don't think it's a good idea to cut off the access, since on computer it's relativery well displayed.

**Comment by FJduFou** [comment]
> C'est pas faux…

Super, vous êtes donc bien un français^^

> Damn it ! I added a big blue button.

Well, that's not too much of a problem

> I don't think it's a good idea to cut off the access, since on computer it's relativery well displayed.

The previous screenshots, come from a computer, **I personally** find that not great ...

**Comment by Heziode** [comment]
Ok… so I'm not going to disable this feature.
However, this needs to be "rewritten".

IMHO, this is not a high priority, but this issue must remain open.

**Comment by FJduFou** [comment]
Could the button at least disappear while waiting for the rewrite?
Just comment out the piece of code (which displays the button) so as not to destroy the work?

**Comment by Heziode** [comment]
No, I still want to leave it for the users where it works for they.

**Comment by FJduFou** [comment]
If you want...

**Comment by JhonnyBn** [comment]
> Damn it ! I added a big blue button.

I must confess that I only clicked the big blue "Tutorial" button when I was translating the site and didn't know where the words were coming from... Never noticed the tutorial before. But I like it, it's a very nice feature. 

Oops... testing it again in GB Investment page, my screen got stuck in black and no tutorial at all...


![image](https://user-images.githubusercontent.com/29382833/101672340-83dde580-3a34-11eb-8e9f-b4bb3b670603.png)

**Comment by Heziode** [comment]
@JhonnyBn, that is a side effect of "purgeCSS", it remove CSS class that is supposed to be not used, but here, shepherd style is used but purgeCSS remove it. I will fix it.
