### ISSUE TITLE
List of monument  in top bar

### ISSUE THREAD

**Issue by babache** [FOE-Tools/FOE-Tools.github.io#398]
Hi,

Is it normal that the list of monuments has disappeared at the top between the logo and the menu button when we are on the page of an investment?

![Capture d’écran 2020-12-05 à 10 50 02](https://user-images.githubusercontent.com/2962513/101239461-02aae980-36e8-11eb-85e5-6f1305e51cd5.png)

I found it practical it avoided having to go back to the top when you are at the bottom of the page for change monuments.

Thx

**Comment by Heziode** [comment]
Indeed it's not normal.
It will be re-added into the release of this sunday night (GMT+1)

**Comment by Heziode** [comment]
This is related to c837463f79ae43e8a0cf65f2bdfe5b3b98ffb1ee.
I forgot to re-add GB List right after:
```
      div.is-hidden-desktop(v-if="['GbInvestment'].indexOf(/^([^_]+)(?:___.+)?$/.exec($route.name)[1]) >= 0")	
        gb-list-select(:current="$route.params.gb" @change="goTo($event)" :only-selector="true")
```

**Comment by babache** [comment]
thx ;)
