### ISSUE TITLE
iOS: copy button not working

### ISSUE THREAD

**Issue by kTitan** [FOE-Tools/FOE-Tools.github.io#40]
On my iOS Devices (iPad/iPhone) the „Copy“ Button is not working. 
The clipboard content does simply not change at all. 

Tested with iOS 11.3 / 11.3.1 with the Safari Browser

**Comment by Heziode** [comment]
I seem is related issue to the module I used for that: [v-clipboard](https://github.com/euvl/v-clipboard/issues/2)

Can you [try this](https://v-copy.egoist.moe/) and tell me if work for you ?

**Comment by Heziode** [comment]
Ok, I will fix that soon.

**Comment by Heziode** [comment]
It is fixed and pushed in prod.
