### ISSUE TITLE
Policies pages doesn't update titles

### ISSUE THREAD

**Issue by JhonnyBn** [FOE-Tools/FOE-Tools.github.io#401]
Clicking on Cookie Policy (in the footer) changes the page to Cookie Policy but the header/title doesn't change. Same thing with Privacy Policy

![image](https://user-images.githubusercontent.com/29382833/101669308-7fafc900-3a30-11eb-8b6d-387488f28806.png)

**Comment by Heziode** [comment]
Ok, I fix it.
