### ISSUE TITLE
Cookies consent translation problem

### ISSUE THREAD

**Issue by JhonnyBn** [FOE-Tools/FOE-Tools.github.io#402]
In languages without translation, this "page" gets blank. To reproduce, click the little cookie in left bottom corner

English:
![image](https://user-images.githubusercontent.com/29382833/101670293-bcc88b00-3a31-11eb-8791-0b638b99598d.png)
Languages not translated:
![image](https://user-images.githubusercontent.com/29382833/101670349-ceaa2e00-3a31-11eb-8e56-dc14fc971639.png)

**Comment by Heziode** [comment]
Indeed…

I just take a look and it is related to the framework that I use for the cookie consent. The text from the button comes from this framework and it have a strange behaviour with the managment of missing translation.

**Comment by Heziode** [comment]
I need to refactor this part in any case (to drop the use of there UI to use a custom one adapated for FOE-Tools), so I think I will fix that at the same time as the rewriting of this part.

**Comment by JhonnyBn** [comment]
Sorry for more issues and thanks for the good work!

**Comment by Heziode** [comment]
Don't apologize for reporting problems.

It help me a lot to identifie new issues. I can't see all problems ;)

**Comment by Heziode** [comment]
Closed by 2fe2936c35d84f78b6ce3a41bf12bb108b7360e3
