### ISSUE TITLE
GBG overview

### ISSUE THREAD

**Issue by Lostchild65** [FOE-Tools/FOE-Tools.github.io#417]
With the updated GBG overview all that is shown now ( on Chrome browser) is the running total of fights between players, no longer is the sun total shown between refreshing the GBG overview. Was this another request/demand from inno?

**Comment by Heziode** [comment]
Hi,

I think you talk about [FOE Assistant](https://chrome.google.com/webstore/detail/foe-helper/bkagcmloachflbbkfmfiggipaelfamdf?hl=fr).
Here is the repo of [FOE Tools](https://foe.tools), not FOE Assistant.

I think you can find help here: https://forum.foe-rechner.de
