### ISSUE TITLE
Wrong calculation, rounding error

### ISSUE THREAD

**Issue by DasRifftierchen** [FOE-Tools/FOE-Tools.github.io#42]
Hi,
I tried with the "Statue of Zeus" in the "GB Investment" tool.
When the "Default rewards" is "5" and the "% of investors bonus" is "85%" then the calculator says that the "Rewards with rate" is "10", but 5*1,85 = 9,25 and so should be "9"
(I didn't check whether the problem occurs on every building and on different values)

**Comment by Heziode** [comment]
Hi @DasRifftierchen,

It does not have any error here, it is the expected state. The result is every rounded to the upper integer.

But maybe it is wrong, what do you gain in game, 9 or 10 FPs ?

**Comment by DasRifftierchen** [comment]
I do gain 9 FP

**Comment by Heziode** [comment]
Ok, so this is a bug. Thank you for reporting, I will fix that soon.
