### ISSUE TITLE
Galata Tower Calculations 

### ISSUE THREAD

**Issue by PromethiusTM** [FOE-Tools/FOE-Tools.github.io#431]
Galata Tower Calcs are not working past level 52

**Comment by Heziode** [comment]
@PromethiusTM I needs more information.

Did you play on beta servers ?
If this is the case, then, InnoGames have moved Galata Tower from No Age to Early Middle Age ([source](https://forum.beta.forgeofempires.com/index.php?threads/galata-tower-changes.14378/)). I am waiting for this change to arrive on the production servers before changing this in FOE-Tools.

If you are not playing on beta servers, sends a screenshot of what you have in game and one of what you have with FOE-Tools.

**Comment by marc1404** [comment]
The base rewards of FOE-tools seem to be off. I'm playing on Greifental, below are two screenshots for the Galata Tower lvl 4 -> 5.
![image](https://user-images.githubusercontent.com/678686/109653168-fb696f80-7b60-11eb-8c6b-6b5afbb0e4a1.png)
![image](https://user-images.githubusercontent.com/678686/109653207-06240480-7b61-11eb-9c00-8643344295fd.png)

**Comment by Heziode** [comment]
Yep, the reward of Galata Tower has change this weeks on production servers.

I will update values this week-end.

**Comment by Heziode** [comment]
Fixed in abaa3542fe94dfbe08b600aace8e321c3ae929ce
