### ISSUE TITLE
[Fair Tade] Display good amounts above 1000

### ISSUE THREAD

**Issue by Beta-Wolf** [FOE-Tools/FOE-Tools.github.io#436]
Dear developers,

**- Suggestion: Please, display the amounts above 1000.** 

It's very useful information for a lot of people, just place a warning next to it that you can't make market offers above 1000 goods instead of not displaying the value of the goods. Please, keep displaying everything above 1000.

![image](https://i.imgur.com/r1qBqp7.png)

**- Link to the site:** 

https://github.com/FOE-Tools/FOE-Tools.github.io/issues

Sincerely,

Bèta Wolf

**Comment by Heziode** [comment]
Thank you for pointing this out.

A current work around is to set "**Split the offers ?**" to "**Yes**" and keep "**Maximum size of an offer**" to **1000**.
