### ISSUE TITLE
Global Settings menu doesn't close on click

### ISSUE THREAD

**Issue by JhonnyBn** [FOE-Tools/FOE-Tools.github.io#455]
If you open the Global settings, clicking outside the modal does not close it, and there is no X button to close it.

Image for better understanding

![image](https://user-images.githubusercontent.com/29382833/117742386-0c76d280-b1db-11eb-9e39-e505c1526414.png)

**Comment by Heziode** [comment]
The close button is at the bottom.

However, like you depict it, the current UX is not good.
