### ISSUE TITLE
PF of the targeted place - select the place

### ISSUE THREAD

**Issue by AntoineBouron** [FOE-Tools/FOE-Tools.github.io#58]
Would it be possible to directly select which place we want to secure instead of putting the "FP of the targeted place" since the information is already loaded on the page?

**Comment by Heziode** [comment]
Are you Agree with this:

![improve_secure-position_in_gb-investment](https://user-images.githubusercontent.com/16735076/41680347-888835de-74d1-11e8-9de5-f322effffdab.png)

**Comment by AntoineBouron** [comment]
I was thinking about button group linked to a field, but this works aswell :)

**Comment by Heziode** [comment]
Ok, so the feature has been merged into #57, So, this feature will be available when this PR will be merged (when the last tool will be done).

**Comment by Heziode** [comment]
It is in production
