### ISSUE TITLE
Implement "Iinvestor Side" of GB-Investment 

### ISSUE THREAD

**Issue by KingSasquatch** [FOE-Tools/FOE-Tools.github.io#60]
Hi,

As I've been growing my Arc, I find myself trying to figure out which GB at which level are profitable once locked in.  I picture a page where the user pic's the GB, and fills in their Arc bonus, then creates a table like the following.

I have done some Python, and Java in the past, but no Node, JS, or any real UI experience.  I'm quite daunted by idea of contributing to this project.

Level | cost | 1st place reward | 1st place result | Cost to secure 1st | Profit(loss)
-- | -- | -- | -- | -- | --
0 → 1 | 60 | 10 | 18.5 | 30 | (11.50)
1 → 2 | 100 | 15 | 27.75 | 50 | (22.25)
2 → 3 | 180 | 20 | 37 | 90 | (53.00)
3 → 4 | 270 | 30 | 55.5 | 135 | (79.50)
4 → 5 | 360 | 40 | 74 | 180 | (106.00)
5 → 6 | 460 | 55 | 101.75 | 230 | (128.25)
6 → 7 | 560 | 65 | 120.25 | 280 | (159.75)
7 → 8 | 670 | 75 | 138.75 | 335 | (196.25)
8 → 9 | 770 | 85 | 157.25 | 385 | (227.75)
9 → 10 | 880 | 100 | 185 | 440 | (255.00)
10 → 11 | 902 | 115 | 212.75 | 451 | (238.25)

**Comment by Heziode** [comment]
Hi,

I do not understand the values in the last column.

**Comment by KingSasquatch** [comment]
Hi,

The last column is the 1st place result minus cost to secure 1st place.  I updated the table to be more explicit.  A couple other things:

- I had also done some rounding, which I removed. 
- My sample table was made using an Arc bonus of 85% (just my current Arc bonus).
- This table is based on Contemporary Era GB info


In my Excel spreadsheet I carried this out through level 80.  I found this useful because I could then see that with my Arc bonus, it's only profitable to secure positions on CE GB levels 31-71.  However, for EMA GB, only levels 42-55 are profitable.

Hopefully, this makes more sense.

**Comment by Heziode** [comment]
Do you mean something like [this (Forecast cost GB Tool)](https://foe-tools.github.io/gb-forecast-cost/?gbfc_gb=Lotus_Temple&gbfc_f=11&gbfc_t=12&gbfc_ipg=85&gbfc_cp=0&gbfc_fp=0&gbfc_ai=0&gbfc_ipc_1=85&gbfc_ipc_2=85&gbfc_ipc_3=85&gbfc_ipc_4=85&gbfc_ipc_5=85) but in table version ? 
The colum "Profit(loss)" is for the owner of the GB ?

**Comment by KingSasquatch** [comment]
That tool is very different.  The Forecast tool tells the GB owner how much they would have to personally invest to level their GB assuming they have people to fill 1-5 to the "award + Arc bonus".  

What I want to know is when is it profitable for me to invest in someone else's GB and how much do I stand to gain.

**Comment by Heziode** [comment]
So something else like [this](https://foe.keiro.ovh/GmBlockingThreshold) (this website are only available is in french) ?

I don't know how you compute the "Cost to secure 1st". If I rely on my tools, the first level need 22 FPs by the owner and no 30, etc.
So the table should be:

Level | cost | 1st place reward | 1st place result | Cost to secure 1st | Profit(loss)
-- | -- | -- | -- | -- | --
0 → 1 | 60 | 10 | 18.5 | 22 | (3.50)
1 → 2 | 100 | 15 | 27.75 | 44 | (16.25)
2 → 3 | 180 | 20 | 37 | 106 | (69.00)
3 → 4 | 270 | 30 | 55.5 | 158 | (102.50)
4 → 5 | 360 | 40 | 74 | 212 | (138.00)
5 → 6 | 460 | 55 | 101.75 | 256 | (154.25)
6 → 7 | 560 | 65 | 120.25 | 320 | (199.75)
7 → 8 | 670 | 75 | 138.75 | 392 | (243.25)
8 → 9 | 770 | 85 | 157.25 | 456 | (298.75)
9 → 10 | 880 | 100 | 185 | 510 | (325.00)
10 → 11 | 902 | 115 | 212.75 | 476 | (263.25)

**Comment by KingSasquatch** [comment]
If I did what your table suggests, someone would come along and put 23FP, and I'd lose 1st place.

Using the "Secure Place" tool, the first few match my numbers.
0->1: https://foe-tools.github.io/secure-position/?sp_lc=60&sp_cd=0&sp_yp=0&sp_op=0&sp_yab=85&sp_ftr=10

1->2: https://foe-tools.github.io/secure-position/?sp_lc=100&sp_cd=0&sp_yp=0&sp_op=0&sp_yab=85&sp_ftr=15

**Comment by KingSasquatch** [comment]
Let me start over.

Here are a couple scenarios:
1) KingSasaquatch wants to make a deal with Heziode.  KingSasquatch would like secure first place over time on Heziode's Cape Canaveral. Heziode doesn't need to swap any FP, and KingSasquatch gets to take 1st.  Given KingSasquatch's Arc Bonus of 85%, and Heziode's Cape current level of 11, can King Sasquatch break-even or profit?  Which levels do profit?

2)  KingSasaquatch wants to make a deal with Heziode.  KingSasquatch would like secure first place over time on Heziode's Cape Canaveral. Heziode needs to swap minimal FP, and KingSasquatch gets to take 1st.  Given KingSasquatch's Arc Bonus of 85%, and Heziode's Cape current level of 11, can King Sasquatch break-even or profit?  How much FP would Heziode need to swap for KingSasquatch to at least break even?

**Comment by KingSasquatch** [comment]
Yes!

**Comment by Heziode** [comment]
Ok, I will implement that as soon as I have a little time :slightly_smiling_face:

**Comment by Heziode** [comment]
I have do that, is it clear ?

[![gbinvestment-innovationtowerfoetools](https://user-images.githubusercontent.com/16735076/42734204-40721152-8840-11e8-8c6c-fd6f8df64d3c.png)](https://user-images.githubusercontent.com/16735076/42734204-40721152-8840-11e8-8c6c-fd6f8df64d3c.png)

**Comment by KingSasquatch** [comment]
Sorry, real life has been hectic.

Yes, I think that prototype looks very good!

Again, I am willing to try, just coming from far behind in writing JS code.

**Comment by Heziode** [comment]
I have put this feature in production in the latest release, With Teracota Army :)

**Comment by Heziode** [comment]
I have created a new issue #66.
