### ISSUE TITLE
Incorrect total invested PF when P5 needs 0

### ISSUE THREAD

**Issue by mestileryan** [FOE-Tools/FOE-Tools.github.io#87]
Hi, I wanted to report the following.
It seems like when P5 needs 0 to be secured, total number is incorrect as it remains 0. However, it is not always the case. In case 1 below, it should remain 48 at the end to end the level. In case 2, I used the same scenario except I slightly decreased the fifth place bonus %. Final number in case 2 is as expected.
If this is the correct behavior, probably the meaning of this cell is confusing, but you can reproduce always this issue, easiest way is to put a high number in "% of investors bonus (arc bonus)".

Case 1 (wrong) : https://i.imgur.com/xJARrdD.png
Case 2 (good) : https://i.imgur.com/oQtpVVF.png

**Comment by Heziode** [comment]
Indeed, this is a bug. I will fix that quickly, but I will probably publish this patch next week.
